function MLoutput = odeEqn(g,r,t,y1)
%ODEEQN
%    MLOUTPUT = ODEEQN(G,R,T,Y1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    23-May-2018 11:03:31

MLoutput = -(accel(t).*cos(y1)+g.*sin(y1))./r;
