function [fitresult, gof] = createFit(HP, MPG)
%CREATEFIT(HP,MPG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : HP
%      Y Output: MPG
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Jun-2017 16:22:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( HP, MPG );

% Set up fittype and options.
ft = fittype( 'b1 + b2/x', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.422835615008808 0.547870901214845];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'MPG vs. HP', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel HP
ylabel MPG
grid on


