function createfigure1(X1, Y1, S1, carData1)
%CREATEFIGURE1(X1, Y1, S1, CARDATA1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  CARDATA1:  scatter c

%  Auto-generated by MATLAB on 23-Jun-2017 16:15:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,S1,carData1);

% Create xlabel
xlabel('Rated HP');

% Create title
title('Fuel Economy');

% Create ylabel
ylabel('MPG');

