%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\jwiken\Seminars\MathModelingWebinar\Demos\1_fuelEconomyCurveFit\dataXLS\2004dat.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/06/30 10:23:40

%% Import the data
[~, ~, raw] = xlsread('C:\Users\jwiken\Seminars\MathModelingWebinar\Demos\1_fuelEconomyCurveFit\dataXLS\2004dat.xlsx','Sheet1','A2:X2338');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[2,3,4,6,8,9,14,17]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,5,7,10,11,12,13,15,16,18,19,20,21,22,23,24]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
carData = table;

%% Allocate imported array to column variable names
carData.Year = data(:,1);
carData.MfrName = categorical(stringVectors(:,1));
carData.CarLine = categorical(stringVectors(:,2));
carData.Car_Truck = categorical(stringVectors(:,3));
carData.EngDisp = data(:,2);
carData.Police = categorical(stringVectors(:,4));
carData.RatedHP = data(:,3);
carData.Transmission = categorical(stringVectors(:,5));
carData.Drive = categorical(stringVectors(:,6));
carData.Weight = data(:,4);
carData.Comp = data(:,5);
carData.AxleRatio = data(:,6);
carData.EVSpeedRatio = data(:,7);
carData.AC = categorical(stringVectors(:,7));
carData.PRP = data(:,8);
carData.FuelType = data(:,9);
carData.City_Highway = categorical(stringVectors(:,8));
carData.HC = data(:,10);
carData.CO = data(:,11);
carData.CO2 = data(:,12);
carData.NOX = data(:,13);
carData.MPG = data(:,14);
carData.Valves_Cyl = data(:,15);
carData.CoastDownTime = data(:,16);

%% Clear temporary variables
clearvars data raw stringVectors R;