function plotCompare(timeseries1,timeseries2,titleinput,Label1,Label2)
% the Void function plotCompare plots 2 simulation outputs. . 
% Inputs: Timeseries structure generated by simulink 'To Workspace' Block.
figure;
labels = {'Control input [su]','Position [m]','Step-reference','Angle filtered[rad]','Angle measured [rad]'};
% Results and comparison
% Output results in following order:
% 1.Control input
% 2. Position in meters
% 3. Reference in meters
% 4. Angle filtered[rad]
% 5. Angle measured [rad]


subplot(311)
plot(timeseries1.Time,timeseries1.Data(:,2),'LineWidth',2);hold on
plot(timeseries2.Time,timeseries2.Data(:,2))
plot(timeseries1.Time,timeseries1.Data(:,3),'k','LineWidth',0.5); 
grid on

title(titleinput);
ylabel(labels{2})
legend(Label1,Label2,labels{3})
xlim([0 15])

subplot(312)
plot(timeseries1.Time,timeseries1.Data(:,4),'LineWidth',2); hold on
plot(timeseries2.Time,timeseries2.Data(:,4))
ylabel(labels{4})
%legend(labels{4})
%legend(Label1,Label2)
xlim([0 15])
grid on

subplot(313)
plot(timeseries1.Time,timeseries1.Data(:,1),'LineWidth',2) ;hold on
plot(timeseries2.Time,timeseries2.Data(:,1))
ylabel(labels{1})
%legend(Label1,Label2)
xlabel('Time[s]');
xlim([0 15])
grid on
end 