function plotsimo(timeseries,titleinput)
% the Void function Plot_timeseries plots the simulation results in 1 figure. 
% Inputs: Timeseries structure generated by simulink 'To Workspace' Block.
%clf
figure;
labels = {'Angle [rad]','Position [m]','Input x-velocity [su]'};
count = 1;

    for i = [1,2,4]%1:size(timeseries.Data,2)
        
        subplot(3,1,count);
        if(count==2)
        plot(timeseries.Time,timeseries.Data(:,i)*0.042177)
        else
        plot(timeseries.Time,timeseries.Data(:,i))
        end
        if(count ==1)
        title(titleinput)
        end
        if i == size(timeseries.Data,2)
           xlabel('Time[s]');
        end
        ylabel(labels(count));
        count = count+1;
    end
end 